// <auto-generated />
using System;
using EcoEnergy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace EcoEnergy.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("SEQ_T_GS24_EMPRESA");

            modelBuilder.HasSequence("SEQ_T_GS24_ENDERECO");

            modelBuilder.HasSequence("SEQ_T_GS24_ORCAMENTO");

            modelBuilder.HasSequence("SEQ_T_GS24_SIMULACAO");

            modelBuilder.HasSequence("SEQ_T_GS24_USUARIO");

            modelBuilder.Entity("EcoEnergy.Models.Empresa", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_EMPRESA")
                        .HasDefaultValueSql("SEQ_T_GS24_EMPRESA.NEXTVAL");

                    b.Property<string>("DsEspecialidade")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("DS_ESPECIALIDADE");

                    b.Property<string>("NmEmpresa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NM_EMPRESA");

                    b.Property<string>("NrCnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)")
                        .HasColumnName("NR_CNPJ");

                    b.Property<string>("NrTelefone")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("NVARCHAR2(13)")
                        .HasColumnName("NR_TELEFONE");

                    b.HasKey("IdEmpresa");

                    b.ToTable("T_GS24_EMPRESA");
                });

            modelBuilder.Entity("EcoEnergy.Models.Endereco", b =>
                {
                    b.Property<int>("IdEndereco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ENDERECO")
                        .HasDefaultValueSql("SEQ_T_GS24_ENDERECO.NEXTVAL");

                    b.Property<string>("DsBairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("DS_BAIRRO");

                    b.Property<string>("DsCep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR2(8)")
                        .HasColumnName("DS_CEP");

                    b.Property<string>("DsCidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("DS_CIDADE");

                    b.Property<string>("DsEstado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("DS_ESTADO");

                    b.Property<string>("DsLogradouro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("DS_LOGRADOURO");

                    b.Property<string>("DsPais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("DS_PAIS");

                    b.Property<int?>("EmpresaIdEmpresa")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_EMPRESA");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<int>("NrLogradouro")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NR_LOGRADOURO");

                    b.Property<int?>("UsuarioIdUsuario")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdEndereco");

                    b.HasIndex("EmpresaIdEmpresa");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("T_GS24_ENDERECO");
                });

            modelBuilder.Entity("EcoEnergy.Models.Orcamento", b =>
                {
                    b.Property<int>("IdOrcamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ORCAMENTO")
                        .HasDefaultValueSql("SEQ_T_GS24_ORCAMENTO.NEXTVAL");

                    b.Property<string>("DsPrazo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("DS_PRAZO");

                    b.Property<string>("DsServicos")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("DS_SERVICOS");

                    b.Property<DateTime>("DtOrcamento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ORCAMENTO");

                    b.Property<int?>("EmpresaIdEmpresa")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_EMPRESA");

                    b.Property<int>("IdSimulacao")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_SIMULACAO");

                    b.Property<double>("NrValorProposto")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("NR_VALOR_PROPOSTO");

                    b.Property<int?>("SimulacaoIdSimulacao")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdOrcamento");

                    b.HasIndex("EmpresaIdEmpresa");

                    b.HasIndex("SimulacaoIdSimulacao");

                    b.ToTable("T_GS24_ORCAMENTO");
                });

            modelBuilder.Entity("EcoEnergy.Models.Simulacao", b =>
                {
                    b.Property<int>("IdSimulacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_SIMULACAO")
                        .HasDefaultValueSql("SEQ_T_GS24_SIMULACAO.NEXTVAL");

                    b.Property<int>("DsOrcamentoSolicitado")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("DS_ORCAMENTO_SOLICITADO");

                    b.Property<DateTime>("DtSimulacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_SIMULACAO");

                    b.Property<int?>("EnderecoIdEndereco")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdEndereco")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ENDERECO");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<double>("NrAreaPlaca")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("NR_AREA_PLACA");

                    b.Property<double>("NrConsumoMensal")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("NR_CONSUMO_MENSAL");

                    b.Property<double>("NrCustoEstimado")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("NR_CUSTO_ESTIMADO");

                    b.Property<double>("NrEconomia")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("NR_ECONOMIA");

                    b.Property<double>("NrPotenciaEstimada")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("NR_POTENCIA_ESTIMADA");

                    b.Property<double>("NrProducaoMensal")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("NR_PRODUCAO_MENSAL");

                    b.Property<double>("NrTempoRetornoInvestimento")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("NR_TEMPO_RETORNO_INVESTIMENTO");

                    b.Property<int?>("UsuarioIdUsuario")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdSimulacao");

                    b.HasIndex("EnderecoIdEndereco");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("T_GS24_SIMULACAO");
                });

            modelBuilder.Entity("EcoEnergy.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO")
                        .HasDefaultValueSql("SEQ_T_GS24_USUARIO.NEXTVAL");

                    b.Property<string>("DsEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("DS_EMAIL");

                    b.Property<int?>("EmpresaIdEmpresa")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_EMPRESA");

                    b.Property<string>("NmUsuario")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("NVARCHAR2(70)")
                        .HasColumnName("NM_USUARIO");

                    b.Property<string>("NrCpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("NVARCHAR2(11)")
                        .HasColumnName("NR_CPF");

                    b.Property<string>("NrTelefone")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("NVARCHAR2(13)")
                        .HasColumnName("NR_TELEFONE");

                    b.HasKey("IdUsuario");

                    b.HasIndex("EmpresaIdEmpresa");

                    b.ToTable("T_GS24_USUARIO");
                });

            modelBuilder.Entity("EcoEnergy.Models.Endereco", b =>
                {
                    b.HasOne("EcoEnergy.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaIdEmpresa");

                    b.HasOne("EcoEnergy.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioIdUsuario");

                    b.Navigation("Empresa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EcoEnergy.Models.Orcamento", b =>
                {
                    b.HasOne("EcoEnergy.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaIdEmpresa");

                    b.HasOne("EcoEnergy.Models.Simulacao", "Simulacao")
                        .WithMany()
                        .HasForeignKey("SimulacaoIdSimulacao");

                    b.Navigation("Empresa");

                    b.Navigation("Simulacao");
                });

            modelBuilder.Entity("EcoEnergy.Models.Simulacao", b =>
                {
                    b.HasOne("EcoEnergy.Models.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoIdEndereco");

                    b.HasOne("EcoEnergy.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioIdUsuario");

                    b.Navigation("Endereco");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EcoEnergy.Models.Usuario", b =>
                {
                    b.HasOne("EcoEnergy.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaIdEmpresa");

                    b.Navigation("Empresa");
                });
#pragma warning restore 612, 618
        }
    }
}
